### ISSUE TITLE
Warn contributors about buffs when adding timed values

### ISSUE THREAD

**Issue by Nkmol** [Nkmol/RoC-Wiki#11]
Should be more clear that we want "clean" values, without buffs applied to it.

**Comment by thadius856** [comment]
I think this is a noble goal.

Held this belief for a while to see if it was feasible, and it seems to be... I think our priority should be to find the assets in the game which determine what those upgrade requirements are (resources, time, pre-preqs), then add them from there. To keep random editors from mucking about in there, migrate just that table of each building to a template and include it in the main article, then protect the included template to moderator+. This would allow new contributors to add stuff to building pages without undoing that work.

Edit: I say this because we see few contributors, even when the barrier to entry is low. In this case, it requires contributors to do (basic) math which is a step farther, and I don't see many (any?) of them actually taking this step. Sort of a once-and-done approach.

**Comment by Nkmol** [comment]
Added by @thadius856 with the [NoticeBuildTimes](https://riseofcivilizations.wikia.com/wiki/Template:NoticeBuildTimes) template.
