### ISSUE TITLE
Improve Item main page

### ISSUE THREAD

**Issue by Nkmol** [Nkmol/RoC-Wiki#5]
The Item main page currently describes every quantity of an item as an individual item. For example every quantity of "wood" (100, 150, 250, 500, etc.) is placed as an individual item, which is true in-game.

This will result in too many unnecessary items, as it is unlikely a User is looking specifically for the "100 Wood" item. In this scenario it is more likely that the User is looking on how to get Wood items in general.

Categorizing such items will improve the item page and reduce scrolling on Mobile.

-----

Suggest categorization for all items that *only differ* in quantity. This includes quantity of time for the different boosts.

**Comment by thadius856** [comment]
I think the current presentation of per-item, _even if they differ only in quantity_, is probably OK. I think the bigger issue is how much space we reserve for each item (e.g., icon size) and thus how many appear on-screen at a time when scrolling down the wiki pages.

**Background**

In-game, on a moderately sized phone, I can view about 16 items on a page. Note that page only takes up perhaps 50% of the screen real estate due to other flair visible. However on a phone that's a pretty moderately small size when we consider how many minutes of angle an item occupies in our vision when holding a phone naturally.

You can experience this by sitting at a computer and viewing the [items page](https://riseofcivilizations.wikia.com/wiki/Items). Now with the game open to the items page, hold your phone in front of you at a comfortable viewing distance. Notice the disparity in the icon sizes. I don't have a second phone handy to demonstrate with a picture, but it's a pretty big disparity if you try for yourself.

**Solution**

I think we could fix this trivially by constraining [Template:BlockGalleryItemItem](https://riseofcivilizations.wikia.com/wiki/Template:BlockGalleryItemItem) to 48 px in either dimension.

**Comment by Nkmol** [comment]
Agree, this can be improved for the Desktop version. Reducing the image size and improving items per columns, does increase readability (Work in progress).
![afbeelding](https://user-images.githubusercontent.com/8686001/48719247-4fb0e580-ec1d-11e8-9a6b-665bbb40b34f.png)

The problem is, however as you already described for the mobile version. Currently, on the mobile version, the images do not give any feedback about the difference (difference in rarity and amount) for each image.
![afbeelding](https://user-images.githubusercontent.com/8686001/48719265-5ccdd480-ec1d-11e8-9d37-d3ed6eea6099.png)

I am somewhat limited about the structure I can apply to the gallery items, as I am using the default [Gallery element](https://community.wikia.com/wiki/Help:Galleries,_Slideshows,_and_Sliders/wikitext) of Wikia. I will see if I can request some assistance of some Wikia Admins. I would really love to have the item text (For example "10 VIP Points") to be on top of the image on the mobile version. Actually exactly how it is in-game.

Hopefully, this described my current struggles 😄 I will keep you up-to-date!

**Comment by Nkmol** [comment]
The new structure has been realised. Items are categorized by 'type' and category.

![afbeelding](https://user-images.githubusercontent.com/8686001/49096106-2241e880-f26a-11e8-9fb7-5e0ff9aed4a0.png)
_https://riseofcivilizations.wikia.com/wiki/Items_

This results in less initial overhead for the visitor and also improves the feedback on mobile as less duplicated images are shown. On mobile, some of the items still do not give enough feedback, like "Treasure of Cave" and "Magic Box". This is however only with a few items, where it previously was practical with all items.

The categorized rarity and image are currently the rarest item of the particular category. This is however still open for discussion and might need a 'categorized' rarity and item image.
